"""add_shipping_address

Revision ID: 0299f115bcf7
Revises: 9431255f1a21
Create Date: 2025-12-11 00:33:46.915879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0299f115bcf7'
down_revision: Union[str, Sequence[str], None] = '9431255f1a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('shipping_name', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('shipping_phone', sa.String(length=20), nullable=True))
    op.add_column('payments', sa.Column('shipping_address', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('shipping_district', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('shipping_province', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('shipping_postal_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'shipping_postal_code')
    op.drop_column('payments', 'shipping_province')
    op.drop_column('payments', 'shipping_district')
    op.drop_column('payments', 'shipping_address')
    op.drop_column('payments', 'shipping_phone')
    op.drop_column('payments', 'shipping_name')
    # ### end Alembic commands ###
