"""add gender to posts

Revision ID: 039dba41f86f
Revises: bb40d686227d
Create Date: 2026-07-02 14:48:06.832915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039dba41f86f'
down_revision: Union[str, Sequence[str], None] = 'bb40d686227d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL on an existing table: backfill existing rows with UNISEX via a
    # server_default, then drop the default so new rows must supply a value.
    op.add_column('posts', sa.Column('gender', sa.Enum('MENS', 'WOMENS', 'UNISEX', name='gender', native_enum=False), nullable=False, server_default='UNISEX'))
    op.alter_column('posts', 'gender', server_default=None)
    op.create_index(op.f('ix_posts_gender'), 'posts', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_gender'), table_name='posts')
    op.drop_column('posts', 'gender')
    # ### end Alembic commands ###
