"""add sizes columns

Revision ID: 03de02091086
Revises: ce94eea0220a
Create Date: 2026-01-03 16:14:19.729773

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '03de02091086'
down_revision: Union[str, Sequence[str], None] = 'ce94eea0220a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('size', sa.String(length=20), nullable=True))
    op.add_column('posts', sa.Column('measurements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_posts_size'), 'posts', ['size'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_size'), table_name='posts')
    op.drop_column('posts', 'measurements')
    op.drop_column('posts', 'size')
    # ### end Alembic commands ###
