"""Add Omise tables

Revision ID: 126312be4cc9
Revises: d3e0698afa9d
Create Date: 2025-12-08 12:36:10.938786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126312be4cc9'
down_revision: Union[str, Sequence[str], None] = 'd3e0698afa9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('omise_recipient_id', sa.String(length=255), nullable=True),
    sa.Column('bank_brand', sa.String(length=64), nullable=True),
    sa.Column('bank_account_last_digits', sa.String(length=4), nullable=True),
    sa.Column('bank_account_name', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='seller_verification_status_enum', create_constraint=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('omise_recipient_id')
    )
    op.create_index(op.f('ix_seller_profiles_created_date'), 'seller_profiles', ['created_date'], unique=False)
    op.create_index(op.f('ix_seller_profiles_id'), 'seller_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_seller_profiles_user_id'), 'seller_profiles', ['user_id'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('omise_charge_id', sa.String(length=255), nullable=True),
    sa.Column('omise_transfer_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.Enum('CARD', 'PROMPTPAY', name='payment_method_enum', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AUTHORIZED', 'SUCCESSFUL', 'FAILED', 'REFUNDED', 'EXPIRED', name='payment_status_enum', create_constraint=True), nullable=False),
    sa.Column('authorize_uri', sa.String(length=512), nullable=True),
    sa.Column('return_uri', sa.String(length=512), nullable=True),
    sa.Column('qr_code_uri', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buyer_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('omise_transfer_id')
    )
    op.create_index(op.f('ix_payments_buyer_id'), 'payments', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_payments_created_date'), 'payments', ['created_date'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_omise_charge_id'), 'payments', ['omise_charge_id'], unique=True)
    op.create_index(op.f('ix_payments_post_id'), 'payments', ['post_id'], unique=False)
    op.create_index(op.f('ix_payments_seller_id'), 'payments', ['seller_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_seller_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_post_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_omise_charge_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_buyer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_seller_profiles_user_id'), table_name='seller_profiles')
    op.drop_index(op.f('ix_seller_profiles_id'), table_name='seller_profiles')
    op.drop_index(op.f('ix_seller_profiles_created_date'), table_name='seller_profiles')
    op.drop_table('seller_profiles')
    # ### end Alembic commands ###
