"""add_deleted_at_to_posts

Revision ID: 31e5c55cef48
Revises: 126312be4cc9
Create Date: 2025-12-10 14:59:02.177164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e5c55cef48'
down_revision: Union[str, Sequence[str], None] = '126312be4cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_deleted_at'), 'posts', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_deleted_at'), table_name='posts')
    op.drop_column('posts', 'deleted_at')
    # ### end Alembic commands ###
