"""add_email_verified_column

Revision ID: 444d920c79d9
Revises: 25db68c57aba
Create Date: 2025-12-05 18:20:06.903665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444d920c79d9'
down_revision: Union[str, Sequence[str], None] = '25db68c57aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column with server_default for existing rows
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # Remove server_default so new rows use Python default
    op.alter_column('users', 'email_verified', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
