"""add transfer_fee to payments

Revision ID: 53a80c00e8cc
Revises: fcbc7f931e94
Create Date: 2026-03-10 11:56:28.463607

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '53a80c00e8cc'
down_revision: Union[str, Sequence[str], None] = 'fcbc7f931e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('transfer_fee', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'transfer_fee')
    # ### end Alembic commands ###
