"""Add Users tables

Revision ID: 6793b7910c18
Revises: 
Create Date: 2025-12-04 01:19:13.488748

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6793b7910c18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'MODERATOR', name='roletype'), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_created_date'), 'user_roles', ['created_date'], unique=False)
    op.create_index(op.f('ix_user_roles_role'), 'user_roles', ['role'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', name='user_status_enum', create_constraint=True), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_date'), 'users', ['created_date'], unique=False)
    op.create_index(op.f('ix_users_email_address'), 'users', ['email_address'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_name', 'users', ['first_name', 'last_name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_to_user_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['user_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    info={'unique_together': [('user_id', 'role_id')]}
    )
    op.create_index(op.f('ix_user_to_user_roles_created_date'), 'user_to_user_roles', ['created_date'], unique=False)
    op.create_index(op.f('ix_user_to_user_roles_role_id'), 'user_to_user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_to_user_roles_user_id'), 'user_to_user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_to_user_roles_user_id'), table_name='user_to_user_roles')
    op.drop_index(op.f('ix_user_to_user_roles_role_id'), table_name='user_to_user_roles')
    op.drop_index(op.f('ix_user_to_user_roles_created_date'), table_name='user_to_user_roles')
    op.drop_table('user_to_user_roles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_address'), table_name='users')
    op.drop_index(op.f('ix_users_created_date'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_roles_role'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_created_date'), table_name='user_roles')
    op.drop_table('user_roles')
    # ### end Alembic commands ###
