"""add_fee_breakdown_to_payments

Revision ID: 737ba82743b6
Revises: a6c9d3bdf7ed
Create Date: 2025-12-12 18:25:13.313093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737ba82743b6'
down_revision: Union[str, Sequence[str], None] = 'a6c9d3bdf7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('item_price', sa.BigInteger(), nullable=True))
    op.add_column('payments', sa.Column('shipping_cost', sa.BigInteger(), nullable=True))
    op.add_column('payments', sa.Column('vat_amount', sa.BigInteger(), nullable=True))
    op.add_column('payments', sa.Column('processing_fee', sa.BigInteger(), nullable=True))
    op.add_column('payments', sa.Column('platform_fee', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'platform_fee')
    op.drop_column('payments', 'processing_fee')
    op.drop_column('payments', 'vat_amount')
    op.drop_column('payments', 'shipping_cost')
    op.drop_column('payments', 'item_price')
    # ### end Alembic commands ###
