"""add feedback table

Revision ID: 96302381c61e
Revises: a747e5b88d16
Create Date: 2026-07-20 16:14:07.842205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96302381c61e'
down_revision: Union[str, Sequence[str], None] = 'a747e5b88d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('payment_id', sa.BigInteger(), nullable=False),
    sa.Column('reviewer_user_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_user_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_feedback_rating'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_created_date'), 'feedback', ['created_date'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_payment_id'), 'feedback', ['payment_id'], unique=True)
    op.create_index(op.f('ix_feedback_reviewer_user_id'), 'feedback', ['reviewer_user_id'], unique=False)
    op.create_index(op.f('ix_feedback_seller_user_id'), 'feedback', ['seller_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_seller_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_reviewer_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_payment_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_date'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
