"""add_user_profile_fields

Revision ID: a22a26696354
Revises: fa5dd2b2cf7e
Create Date: 2026-01-16 19:32:11.253194

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a22a26696354'
down_revision: Union[str, Sequence[str], None] = 'fa5dd2b2cf7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('show_full_name', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'show_full_name')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
