"""user softdelete

Revision ID: a616bca8a5db
Revises: fd9a6162e248
Create Date: 2025-12-10 17:05:30.996685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a616bca8a5db'
down_revision: Union[str, Sequence[str], None] = 'fd9a6162e248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'buyer_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('payments', 'seller_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('payments', 'post_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('payments_seller_id_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('payments_buyer_id_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('payments_post_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key('payments_post_id_fkey', 'payments', 'posts', ['post_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('payments_buyer_id_fkey', 'payments', 'users', ['buyer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('payments_seller_id_fkey', 'payments', 'users', ['seller_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('posts', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('posts_user_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('posts', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('payments_seller_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('payments_buyer_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('payments_post_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key('payments_post_id_fkey', 'payments', 'posts', ['post_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('payments_buyer_id_fkey', 'payments', 'users', ['buyer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('payments_seller_id_fkey', 'payments', 'users', ['seller_id'], ['id'], ondelete='SET NULL')
    op.alter_column('payments', 'post_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('payments', 'seller_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('payments', 'buyer_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
