"""add_shipping_cost_to_posts

Revision ID: a6c9d3bdf7ed
Revises: 0299f115bcf7
Create Date: 2025-12-12 11:47:20.059029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c9d3bdf7ed'
down_revision: Union[str, Sequence[str], None] = '0299f115bcf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column with server_default for existing rows, then remove default
    op.add_column('posts', sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.alter_column('posts', 'shipping_cost', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'shipping_cost')
    # ### end Alembic commands ###
