"""convert enums to varchar

Revision ID: bb40d686227d
Revises: e2f9a1c4b8d6
Create Date: 2026-07-01 22:24:58.888798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb40d686227d'
down_revision: Union[str, Sequence[str], None] = 'e2f9a1c4b8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_flags', 'status',
               existing_type=postgresql.ENUM('PENDING', 'DISMISSED', name='message_flag_status_enum'),
               type_=sa.Enum('PENDING', 'DISMISSED', name='messageflagstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=postgresql.ENUM('CARD', 'PROMPTPAY', name='payment_method_enum'),
               type_=sa.Enum('CARD', 'PROMPTPAY', name='paymentmethod', native_enum=False),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'AUTHORIZED', 'SUCCESSFUL', 'FAILED', 'REFUNDED', 'EXPIRED', 'DISPUTED', 'REFUND_REQUIRED', name='payment_status_enum'),
               type_=sa.Enum('PENDING', 'AUTHORIZED', 'SUCCESSFUL', 'FAILED', 'REFUNDED', 'EXPIRED', 'DISPUTED', 'REFUND_REQUIRED', name='paymentstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('payments', 'fulfillment_status',
               existing_type=postgresql.ENUM('PACKING', 'IN_TRANSIT', 'DELIVERED', name='fulfillment_status_enum'),
               type_=sa.Enum('PACKING', 'IN_TRANSIT', 'DELIVERED', name='fulfillmentstatus', native_enum=False),
               existing_nullable=True)
    op.alter_column('payments', 'shipping_carrier',
               existing_type=postgresql.ENUM('EMS', 'KEX', 'FLASH_EXPRESS', 'J_AND_T', name='shipping_carrier_enum'),
               type_=sa.Enum('EMS', 'KEX', 'FLASH_EXPRESS', 'J_AND_T', name='shippingcarrier', native_enum=False),
               existing_nullable=True)
    op.alter_column('posts', 'type',
               existing_type=postgresql.ENUM('SHIRT', 'PANTS', 'JACKET', 'SHOES', 'ACCESSORIES', 'OTHER', name='post_type_enum'),
               type_=sa.Enum('SHIRT', 'PANTS', 'JACKET', 'SHOES', 'ACCESSORIES', 'OTHER', name='posttype', native_enum=False),
               existing_nullable=False)
    op.alter_column('reports', 'report_type',
               existing_type=postgresql.ENUM('USER', 'POST', name='report_type_enum'),
               type_=sa.Enum('USER', 'POST', name='reporttype', native_enum=False),
               existing_nullable=False)
    op.alter_column('reports', 'reason',
               existing_type=postgresql.ENUM('COUNTERFEIT', 'ABUSE_OF_SYSTEM', 'PROHIBITED_ITEM', 'SCAM', name='report_reason_enum'),
               type_=sa.Enum('COUNTERFEIT', 'ABUSE_OF_SYSTEM', 'PROHIBITED_ITEM', 'SCAM', name='reportreason', native_enum=False),
               existing_nullable=False)
    op.alter_column('reports', 'status',
               existing_type=postgresql.ENUM('PENDING', 'REVIEWED', 'RESOLVED', 'DISMISSED', name='report_status_enum'),
               type_=sa.Enum('PENDING', 'REVIEWED', 'RESOLVED', 'DISMISSED', name='reportstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('seller_invites', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'USED', 'REVOKED', name='invite_status_enum'),
               type_=sa.Enum('ACTIVE', 'USED', 'REVOKED', name='invitestatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('seller_profiles', 'verification_status',
               existing_type=postgresql.ENUM('PENDING', 'VERIFIED', 'REJECTED', name='seller_verification_status_enum'),
               type_=sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='sellerverificationstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('user_roles', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', 'MODERATOR', name='roletype'),
               type_=sa.Enum('ADMIN', 'USER', 'MODERATOR', name='roletype', native_enum=False),
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACTIVE', name='user_status_enum'),
               type_=sa.Enum('PENDING', 'ACTIVE', name='userstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###
    # Columns are now VARCHAR; drop the orphaned native enum types.
    for type_name in (
        'message_flag_status_enum', 'payment_method_enum', 'payment_status_enum',
        'fulfillment_status_enum', 'shipping_carrier_enum', 'post_type_enum',
        'report_type_enum', 'report_reason_enum', 'report_status_enum',
        'invite_status_enum', 'seller_verification_status_enum', 'roletype',
        'user_status_enum',
    ):
        op.execute(f'DROP TYPE {type_name}')


def downgrade() -> None:
    """Downgrade schema."""
    # Recreate the native enum types before the columns are cast back to them.
    for type_name, values in (
        ('user_status_enum', ('PENDING', 'ACTIVE')),
        ('roletype', ('ADMIN', 'USER', 'MODERATOR')),
        ('seller_verification_status_enum', ('PENDING', 'VERIFIED', 'REJECTED')),
        ('invite_status_enum', ('ACTIVE', 'USED', 'REVOKED')),
        ('report_status_enum', ('PENDING', 'REVIEWED', 'RESOLVED', 'DISMISSED')),
        ('report_reason_enum', ('COUNTERFEIT', 'ABUSE_OF_SYSTEM', 'PROHIBITED_ITEM', 'SCAM')),
        ('report_type_enum', ('USER', 'POST')),
        ('post_type_enum', ('SHIRT', 'PANTS', 'JACKET', 'SHOES', 'ACCESSORIES', 'OTHER')),
        ('shipping_carrier_enum', ('EMS', 'KEX', 'FLASH_EXPRESS', 'J_AND_T')),
        ('fulfillment_status_enum', ('PACKING', 'IN_TRANSIT', 'DELIVERED')),
        ('payment_status_enum', ('PENDING', 'AUTHORIZED', 'SUCCESSFUL', 'FAILED',
                                 'REFUNDED', 'EXPIRED', 'DISPUTED', 'REFUND_REQUIRED')),
        ('payment_method_enum', ('CARD', 'PROMPTPAY')),
        ('message_flag_status_enum', ('PENDING', 'DISMISSED')),
    ):
        members = ', '.join(f"'{v}'" for v in values)
        op.execute(f'CREATE TYPE {type_name} AS ENUM ({members})')
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', name='userstatus', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'ACTIVE', name='user_status_enum'),
               existing_nullable=False)
    op.alter_column('user_roles', 'role',
               existing_type=sa.Enum('ADMIN', 'USER', 'MODERATOR', name='roletype', native_enum=False),
               type_=postgresql.ENUM('ADMIN', 'USER', 'MODERATOR', name='roletype'),
               existing_nullable=False)
    op.alter_column('seller_profiles', 'verification_status',
               existing_type=sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='sellerverificationstatus', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'VERIFIED', 'REJECTED', name='seller_verification_status_enum'),
               existing_nullable=False)
    op.alter_column('seller_invites', 'status',
               existing_type=sa.Enum('ACTIVE', 'USED', 'REVOKED', name='invitestatus', native_enum=False),
               type_=postgresql.ENUM('ACTIVE', 'USED', 'REVOKED', name='invite_status_enum'),
               existing_nullable=False)
    op.alter_column('reports', 'status',
               existing_type=sa.Enum('PENDING', 'REVIEWED', 'RESOLVED', 'DISMISSED', name='reportstatus', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'REVIEWED', 'RESOLVED', 'DISMISSED', name='report_status_enum'),
               existing_nullable=False)
    op.alter_column('reports', 'reason',
               existing_type=sa.Enum('COUNTERFEIT', 'ABUSE_OF_SYSTEM', 'PROHIBITED_ITEM', 'SCAM', name='reportreason', native_enum=False),
               type_=postgresql.ENUM('COUNTERFEIT', 'ABUSE_OF_SYSTEM', 'PROHIBITED_ITEM', 'SCAM', name='report_reason_enum'),
               existing_nullable=False)
    op.alter_column('reports', 'report_type',
               existing_type=sa.Enum('USER', 'POST', name='reporttype', native_enum=False),
               type_=postgresql.ENUM('USER', 'POST', name='report_type_enum'),
               existing_nullable=False)
    op.alter_column('posts', 'type',
               existing_type=sa.Enum('SHIRT', 'PANTS', 'JACKET', 'SHOES', 'ACCESSORIES', 'OTHER', name='posttype', native_enum=False),
               type_=postgresql.ENUM('SHIRT', 'PANTS', 'JACKET', 'SHOES', 'ACCESSORIES', 'OTHER', name='post_type_enum'),
               existing_nullable=False)
    op.alter_column('payments', 'shipping_carrier',
               existing_type=sa.Enum('EMS', 'KEX', 'FLASH_EXPRESS', 'J_AND_T', name='shippingcarrier', native_enum=False),
               type_=postgresql.ENUM('EMS', 'KEX', 'FLASH_EXPRESS', 'J_AND_T', name='shipping_carrier_enum'),
               existing_nullable=True)
    op.alter_column('payments', 'fulfillment_status',
               existing_type=sa.Enum('PACKING', 'IN_TRANSIT', 'DELIVERED', name='fulfillmentstatus', native_enum=False),
               type_=postgresql.ENUM('PACKING', 'IN_TRANSIT', 'DELIVERED', name='fulfillment_status_enum'),
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('PENDING', 'AUTHORIZED', 'SUCCESSFUL', 'FAILED', 'REFUNDED', 'EXPIRED', 'DISPUTED', 'REFUND_REQUIRED', name='paymentstatus', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'AUTHORIZED', 'SUCCESSFUL', 'FAILED', 'REFUNDED', 'EXPIRED', 'DISPUTED', 'REFUND_REQUIRED', name='payment_status_enum'),
               existing_nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.Enum('CARD', 'PROMPTPAY', name='paymentmethod', native_enum=False),
               type_=postgresql.ENUM('CARD', 'PROMPTPAY', name='payment_method_enum'),
               existing_nullable=False)
    op.alter_column('message_flags', 'status',
               existing_type=sa.Enum('PENDING', 'DISMISSED', name='messageflagstatus', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'DISMISSED', name='message_flag_status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
