"""add_seller_invites_reports_bans

Revision ID: ce94eea0220a
Revises: 1fe65bf8d5df
Create Date: 2025-12-28 00:26:03.307652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce94eea0220a'
down_revision: Union[str, Sequence[str], None] = '1fe65bf8d5df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_invites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'REVOKED', name='invite_status_enum', create_constraint=True), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('used_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_invites_code'), 'seller_invites', ['code'], unique=True)
    op.create_index(op.f('ix_seller_invites_created_by_user_id'), 'seller_invites', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_seller_invites_created_date'), 'seller_invites', ['created_date'], unique=False)
    op.create_index(op.f('ix_seller_invites_id'), 'seller_invites', ['id'], unique=False)
    op.create_index(op.f('ix_seller_invites_status'), 'seller_invites', ['status'], unique=False)
    op.create_index(op.f('ix_seller_invites_used_by_user_id'), 'seller_invites', ['used_by_user_id'], unique=False)
    op.create_table('user_bans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('banned_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('lifted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifted_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['banned_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lifted_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bans_created_date'), 'user_bans', ['created_date'], unique=False)
    op.create_index(op.f('ix_user_bans_id'), 'user_bans', ['id'], unique=False)
    op.create_index(op.f('ix_user_bans_is_active'), 'user_bans', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_bans_user_id'), 'user_bans', ['user_id'], unique=False)
    op.create_table('post_bans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('banned_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('lifted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifted_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['banned_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lifted_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_bans_created_date'), 'post_bans', ['created_date'], unique=False)
    op.create_index(op.f('ix_post_bans_id'), 'post_bans', ['id'], unique=False)
    op.create_index(op.f('ix_post_bans_is_active'), 'post_bans', ['is_active'], unique=False)
    op.create_index(op.f('ix_post_bans_post_id'), 'post_bans', ['post_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('reporter_user_id', sa.BigInteger(), nullable=False),
    sa.Column('report_type', sa.Enum('USER', 'POST', name='report_type_enum', create_constraint=True), nullable=False),
    sa.Column('reported_user_id', sa.BigInteger(), nullable=True),
    sa.Column('reported_post_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Enum('COUNTERFEIT', 'ABUSE_OF_SYSTEM', 'PROHIBITED_ITEM', 'SCAM', name='report_reason_enum', create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'RESOLVED', 'DISMISSED', name='report_status_enum', create_constraint=True), nullable=False),
    sa.Column('reviewed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reported_post_id'], ['posts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_date'), 'reports', ['created_date'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_reason'), 'reports', ['reason'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_reported_post_id'), 'reports', ['reported_post_id'], unique=False)
    op.create_index(op.f('ix_reports_reported_user_id'), 'reports', ['reported_user_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_user_id'), 'reports', ['reporter_user_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_post_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_reason'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_date'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_post_bans_post_id'), table_name='post_bans')
    op.drop_index(op.f('ix_post_bans_is_active'), table_name='post_bans')
    op.drop_index(op.f('ix_post_bans_id'), table_name='post_bans')
    op.drop_index(op.f('ix_post_bans_created_date'), table_name='post_bans')
    op.drop_table('post_bans')
    op.drop_index(op.f('ix_user_bans_user_id'), table_name='user_bans')
    op.drop_index(op.f('ix_user_bans_is_active'), table_name='user_bans')
    op.drop_index(op.f('ix_user_bans_id'), table_name='user_bans')
    op.drop_index(op.f('ix_user_bans_created_date'), table_name='user_bans')
    op.drop_table('user_bans')
    op.drop_index(op.f('ix_seller_invites_used_by_user_id'), table_name='seller_invites')
    op.drop_index(op.f('ix_seller_invites_status'), table_name='seller_invites')
    op.drop_index(op.f('ix_seller_invites_id'), table_name='seller_invites')
    op.drop_index(op.f('ix_seller_invites_created_date'), table_name='seller_invites')
    op.drop_index(op.f('ix_seller_invites_created_by_user_id'), table_name='seller_invites')
    op.drop_index(op.f('ix_seller_invites_code'), table_name='seller_invites')
    op.drop_table('seller_invites')
    op.execute('DROP TYPE invite_status_enum')
    op.execute('DROP TYPE report_type_enum')
    op.execute('DROP TYPE report_reason_enum')
    op.execute('DROP TYPE report_status_enum')


    # ### end Alembic commands ###
