"""add fee free sales promo fields

Revision ID: cfec8a100645
Revises: bdae1670365d
Create Date: 2026-06-10 13:10:26.988051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfec8a100645'
down_revision: Union[str, Sequence[str], None] = 'bdae1670365d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('platform_fee_waived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('seller_invites', sa.Column('fee_free_sales', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('seller_profiles', sa.Column('fee_free_sales_remaining', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_profiles', 'fee_free_sales_remaining')
    op.drop_column('seller_invites', 'fee_free_sales')
    op.drop_column('payments', 'platform_fee_waived')
    # ### end Alembic commands ###
