"""add_seller_payout_to_payments

Revision ID: d92f658b9225
Revises: 737ba82743b6
Create Date: 2025-12-17 23:28:51.770229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92f658b9225'
down_revision: Union[str, Sequence[str], None] = '737ba82743b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('seller_payout', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'seller_payout')
    # ### end Alembic commands ###
