"""add message_flags table

Revision ID: fcbc7f931e94
Revises: 9722de05afda
Create Date: 2026-03-04 12:59:33.827196

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fcbc7f931e94"
down_revision: Union[str, Sequence[str], None] = "9722de05afda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_flags",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("conversation_id", sa.BigInteger(), nullable=False),
        sa.Column("sender_id", sa.BigInteger(), nullable=False),
        sa.Column("matched_patterns", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "DISMISSED",
                name="message_flag_status_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_modified_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_message_flags_conversation_id"),
        "message_flags",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_flags_created_date"),
        "message_flags",
        ["created_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_flags_message_id"),
        "message_flags",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_flags_sender_id"), "message_flags", ["sender_id"], unique=False
    )
    op.create_index(
        op.f("ix_message_flags_status"), "message_flags", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_flags_status"), table_name="message_flags")
    op.drop_index(op.f("ix_message_flags_sender_id"), table_name="message_flags")
    op.drop_index(op.f("ix_message_flags_message_id"), table_name="message_flags")
    op.drop_index(op.f("ix_message_flags_created_date"), table_name="message_flags")
    op.drop_index(op.f("ix_message_flags_conversation_id"), table_name="message_flags")
    op.drop_table("message_flags")
    # ### end Alembic commands ###
