// AUTO-GENERATED from backend/app/constants/post.py — do not edit.
// Regenerate: pipenv run python scripts/gen_frontend_enums.py

export const POST_CATEGORIES = [
  "TOPS",
  "BOTTOMS",
  "OUTERWEAR",
  "FOOTWEAR",
  "ACCESSORIES",
  "TAILORING",
  "DRESSES",
  "JEWELRY",
  "BAGS",
] as const;
export type PostCategory = (typeof POST_CATEGORIES)[number];

export const POST_GENDERS = [
  "MENS",
  "WOMENS",
  "UNISEX",
] as const;
export type Gender = (typeof POST_GENDERS)[number];

export const SIZE_GROUPS = [
  "LETTER",
  "WAIST",
  "SHOE",
  "SUIT",
  "ONE_SIZE",
] as const;
export type SizeGroup = (typeof SIZE_GROUPS)[number];

// Flat list of every subcategory code (the gendered tree is served via
// GET /categories); used to validate subcategory URL params.
export const SUBCATEGORIES = [
  "BELTS",
  "BLAZERS",
  "BOMBERS",
  "BOOTS",
  "DENIM_JACKETS",
  "GLASSES",
  "HATS",
  "HI_TOP_SNEAKERS",
  "LEATHER_JACKETS",
  "LEGGINGS",
  "LONG_SLEEVE_T_SHIRTS",
  "LOW_TOP_SNEAKERS",
  "MISCELLANEOUS",
  "POLOS",
  "SANDALS",
  "SHORTS",
  "SHORT_SLEEVE_T_SHIRTS",
  "SLIP_ONS",
  "SUNGLASSES",
  "VESTS",
  "WALLETS",
  "BAGS_AND_LUGGAGE",
  "CASUAL_LEATHER_SHOES",
  "CASUAL_PANTS",
  "CLOAKS_AND_CAPES",
  "CROPPED_PANTS",
  "DENIM",
  "FORMAL_SHIRTING",
  "FORMAL_SHOES",
  "FORMAL_TROUSERS",
  "GLOVES_AND_SCARVES",
  "HEAVY_COATS",
  "JERSEYS",
  "JEWELRY_AND_WATCHES",
  "LIGHT_JACKETS",
  "OVERALLS_AND_JUMPSUITS",
  "PARKAS",
  "RAINCOATS",
  "SHIRTS_BUTTON_UPS",
  "SOCKS_AND_UNDERWEAR",
  "SUITS",
  "SWEATERS_AND_KNITWEAR",
  "SWEATPANTS_AND_JOGGERS",
  "SWEATSHIRTS_AND_HOODIES",
  "SWIMWEAR",
  "TANK_TOPS_AND_SLEEVELESS",
  "TIES_AND_POCKETSQUARES",
  "TUXEDOS",
  "BACKPACKS",
  "BELT_BAGS",
  "BLOUSES",
  "BODYSUITS",
  "BRACELETS",
  "BUCKET_BAGS",
  "BUTTON_UPS",
  "CLUTCHES",
  "COATS",
  "CROP_TOPS",
  "CROSSBODY_BAGS",
  "DOWN_JACKETS",
  "EARRINGS",
  "FLATS",
  "FUR_AND_FAUX_FUR",
  "GLOVES",
  "GOWNS",
  "HAIR_ACCESSORIES",
  "HANDLE_BAGS",
  "HEELS",
  "HOBO_BAGS",
  "HOODIES",
  "JACKETS",
  "JEANS",
  "JUMPSUITS",
  "LUGGAGE_AND_TRAVEL",
  "MAXI_DRESSES",
  "MAXI_SKIRTS",
  "MESSENGERS_AND_SATCHELS",
  "MIDI_DRESSES",
  "MIDI_SKIRTS",
  "MINI_BAGS",
  "MINI_DRESSES",
  "MINI_SKIRTS",
  "MULES",
  "NECKLACES",
  "OTHER",
  "PANTS",
  "PLATFORMS",
  "RAIN_JACKETS",
  "RINGS",
  "SCARVES",
  "SHOULDER_BAGS",
  "SOCKS_AND_INTIMATES",
  "SWEATERS",
  "SWEATSHIRTS",
  "TANK_TOPS",
  "TOTE_BAGS",
  "WATCHES",
] as const;
export type Subcategory = (typeof SUBCATEGORIES)[number];

export const LETTER_SIZES = [
  "XS",
  "S",
  "M",
  "L",
  "XL",
  "XXL",
  "XXXL",
] as const;

export const WAIST_SIZES = [
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
] as const;

export const SUIT_SIZES = [
  "34",
  "36",
  "38",
  "40",
  "42",
  "44",
  "46",
  "48",
  "50",
] as const;

export const SHOE_SIZES = [
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
] as const;
